### ISSUE TITLE
short URIs are not used inside the @context node (outputing from Jena)

### ISSUE THREAD

**Issue by fpservant** [jsonld-java/jsonld-java#140] opened 2015-05-05 21:24 UTC
(as in previous issue, using Jena setNSPrefix)

package sometests;
import org.junit.Test;
import com.hp.hpl.jena.rdf.model.Model;
import com.hp.hpl.jena.rdf.model.ModelFactory;
import com.hp.hpl.jena.rdf.model.Property;
import com.hp.hpl.jena.rdf.model.Resource;

public class JsonLDWriterTest {
@Test
/** short URIs are not used inside the @context node */
public final void test2() {
	Model m = ModelFactory.createDefaultModel();
	String url = "http://www.a.com/foo/";
	Resource s = m.createResource(url + "s");
	Property p = m.createProperty(url + "p");
	Resource o = m.createResource(url + "o");
	m.add(s,p,o);
	m.setNsPrefix("ex",url);
	m.write(System.out, "JSON-LD");
	System.out.println();
	
	// we get 
	
	/*
	{
	  "@id" : "ex:s",
	  "p" : "ex:o",
	  "@context" : {
	    "p" : {
	      "@id" : "http://www.a.com/foo/p",
	      "@type" : "@id"
	    },
	    "ex" : "http://www.a.com/foo/"
	  }
	}
	*/
	
	// why not:
	
	/*
	{
	  "@id" : "ex:s",
	  "p" : "ex:o",
	  "@context" : {
	    "p" : {
	      "@id" : "ex:p",
	      "@type" : "@id"
	    },
	    "ex" : "http://www.a.com/foo/"
	  }
	}
 */
}

}

**Comment by ansell** [comment] 2015-05-05 22:44
@afs, is this an issue that should be tracked on the Apache Jira for Jena or is it a bug in the core?

**Comment by afs** [comment] 2015-05-06 08:29
@ansell - it looks like jsonld-core.  There isn't a way to control this from the jsonld-core API, is there?

Checking, this looks to apply to all the issues labelled "jena" in the issue tracker.  It just the route by which they are coming to people's attention.

Jena sets the call to jsonld-java and isn't doing anything to manipulate the JSON. (if it is the way Jena calls jsonld-core, then do push back :  the Jena code is in [JsonLDWriter](https://github.com/apache/jena/blob/master/jena-arq/src/main/java/org/apache/jena/riot/out/JsonLDWriter.java).

**Comment by afs** [comment] 2015-05-06 08:32
@fpservant - the people here don't necessarily speak fluent Jena. If the reports could be RDF in, JSON-LD out, it might be clearer:

The input graph for test2 is 
```
@prefix ex:    <http://www.a.com/foo/> .

ex:s    ex:p    ex:o .

```

**Comment by fpservant** [comment] 2015-05-06 09:20
@afs thank you for your remark. I edited my reports to include Jena's output in turtle

**Comment by ansell** [comment] 2015-11-16 03:20
Jena could fix this by doing the compaction at the following and similar locations:

https://github.com/apache/jena/blob/master/jena-arq/src/main/java/org/apache/jena/riot/out/JsonLDWriter.java#L147

I have added a test to ensure that the results are syntactically valid and the compaction does not result in the full IRI appearing when it is loaded into the RDFDataset API using addTriple and setNamespace, so it seems like the code you reference is being set in the context directly by Jena and then not being modified by JSONLD-Java.

The references that I can find in JSON-LD-API-1.0 (in Section 6) all seem to reference the expansion of terms in the context rather than the compaction. 

I am closing this as compaction will still occur for the IRIs outside of the context, and the spec doesn't seem to require it or specify steps that produce compacted IRIs inside of the context.

**Closed by ansell** 2015-11-16 03:20 UTC
Labels: Integration, Jena

**Comment by afs** [comment] 2015-12-04 10:48
Not sure Jena can - it does not know about compaction, and relies on the algorithms of jsonld-java. If the specs do not specify compaction of the context, it will lead to less unexpected behaviour from comparing the output of different systems if the specs are followed without additional processing.
