### ISSUE TITLE
ConcurrentModificationException at JsonLdProcessor.frame(...)

### ISSUE THREAD

**Issue by KMax** [jsonld-java/jsonld-java#166] opened 2016-02-26 18:12 UTC
I faced a ConcurrentModificationException thrown from JsonLdProcessor.frame(...). I minimized input and frame snippets to remove irrelevant pieces. 

_The snippets may look quite strange, but they were derived from a real use case_ :)

The input snippet:
```
{
    "@context": {
        "net": "http://www.example.net/",
        "org": "http://example.org/",
        "com": "http://example.com/",

        "org:p3": { "@type": "@id" }
    },
    "com:p1":[
      {
        "org:p3": "_:b2",
        "net:p2": {}
      },
      {
        "@id": "_:b2",
        "net:p2": {}
      }
    ]
}
```

and frame:
```
{
    "@context": {
        "net": "http://www.example.net/",
        "org": "http://example.org/",
        "com": "http://example.com/",

        "org:p3": { "@type": "@id" }
    },
    "com:p1": {}
}
```

Also I've implemented a unit test in my [fork](https://github.com/KMax/jsonld-java/commit/e00b8a2eca5a965a0caceb68cdadf82c9b275cb8), so everyone could easily reproduce the issue.

Notes:
* changing the number of prefixes fixes the issue, e.g. by replacing `org` prefix with `net`, so `org:p3` become `net:p3`,
* removing `www.` from the `net` prefix fixes the issue,
* placing `_:b2` before the other object fixes the issue. _I use this workaround in my use case_,
* everything works fine in [JsonLd Playground](http://json-ld.org/playground/).

**Comment by ansell** [comment] 2016-02-28 21:55
Thanks for the minimal testcase! I will look into the cause.

**Comment by ansell** [comment] 2016-02-28 22:17
Fixed by taking a defensive copy of the keyset in question before iterating over it. Thanks for spotting it!

**Closed** 2016-02-28 22:17 UTC
