### ISSUE TITLE
How to set the ouput's @context to a URI?

### ISSUE THREAD

**Issue by fpservant** [jsonld-java/jsonld-java#184] opened 2016-09-06 12:17 UTC
How do you set the @context in a compact output to be, for instance:
"@context": "http://schema.org/"
?

I think that this should work, but I doesn't:

```
@Test public void testX() throws JsonParseException, IOException, JsonLdError {
    // loading a simple jsonld with an external context
    String jsonld = "{\"@id\":\"_:b0\",\"jobTitle\":\"Professor\",\"name\":\"Jane Doe\",\"@context\":\"http://schema.org/\"}";      
    Object jsonObject = JsonUtils.fromString(jsonld);   
    JsonLdOptions options = new JsonLdOptions();

    // verify that the external context is correctly processed
    Object expand = JsonLdProcessor.expand(jsonObject, options);
    System.out.println("-- expand: ");
    System.out.println(JsonUtils.toPrettyString(expand));
    assertTrue(JsonUtils.toPrettyString(expand).indexOf("http://schema.org/name") > -1);

    // but how do I get the context in compact's output?
    Map context = new HashMap();
    context.put("@context", "http://schema.org/");
    Object compact = JsonLdProcessor.compact(jsonObject, context, options);
    System.out.println("-- compact: ");
    System.out.println(JsonUtils.toPrettyString(compact));
    // this fails:
    assertTrue(JsonUtils.toPrettyString(compact).indexOf("@context") > -1);
}
```

Here is what we get for JsonUtils.toPrettyString(compact). It's not JSON-LD:

```
{
  "id" : "_:b0",
  "jobTitle" : "Professor",
  "name" : "Jane Doe"
}
```

**Comment by fpservant** [comment] 2016-09-06 12:35
BTW, how do I get the content of the downloaded context?

**Comment by ansell** [comment] 2016-09-07 00:46
I don't know whether it is possible to avoid the context being dereferenced as part of the compact operation:

https://www.w3.org/TR/json-ld-api/#compaction-algorithm

That algorithm triggers the following algorithm if you supply a string that looks like a URL, which should replace the URL with the results of resolving it:

https://www.w3.org/TR/json-ld-api/#context-processing-algorithm

If you need to hack around it, you could replace or add the @context key to the result map with your desired content.

There is no access to the underlying downloaded context unless you extend DocumentLoader and save the results yourself in your version of loadDocument(URL).

Alternatively, you could use the non-Public-API methods in JsonUtils to resolve the context URL manually but those method signatures are prone to change so your code may not be stable over time.

**Comment by fpservant** [comment] 2016-09-09 06:24
Thanks.

I must confess that I have some perplexity regarding the way one is supposed to use the API. This is probably related to the fact that the arguments of methods are of class Object. For instance, how do I know that the context param is supposed to be a Map?
Other example:
If I parse a jsonld document that contains an "@context", and then I want to output it in compact or flatten format. I need to pass the context to the ``compact`` or the ``flatten`` method. How do I get it from the ``Object`` returned by ``JsonUtils.fromInputStream``? Am I supposed to test whether this object is a Map, which contain an "@context" key, and if yes, then I can take the corresponding value and pass it as the context param of the method?
I know that this works today. But will it still work in the future?

Is there some document about the API that I missed?

It would probably be useful if the API were defining a JsonLDObject class. 

Best Regards

**Comment by ansell** [comment] 2016-09-11 23:13
The major obstacle is that the JSONLD-API specification isn't typesafe. Ie, there are numerous instances where it specifies that there should be a check on whether a node is a list or not, and branch depending on the result. There even some instances asking to check whether something is a String or not and branch on the result, so it isn't trivial to take what we have right now and make it typesafe. The manner in which generics are implemented in Java also makes it difficult to implement. I.e., we drop down all the way to Map&lt;String, Object&gt; in virtually every case because the object itself has no way of advertising Object as its real value even if it is known to always be List or Map.

For the moment, JsonUtils methods should continue to return Map, and even if I make it typesafe I would try to implement Map for the root node if possible to preserve its usefulness.

I don't think the JSONLD-API was designed with the capability of persisting pretty-printed references like @context strings or @context arrays. Hence, I am not sure what a persistent way to do this is at this moment. The API here is not yet at 1.0 (mostly due to JsonUtils and its reuse but also the Map/Object issues) I am not willing to commit to a particular method right now but will look into it.

One enhancement that I have been thinking about but haven't implemented would be a multi-method Handler, which could handle @context declarations and resolutions. This would likely be an extension or generification of DocumentLoader but it hasn't occurred yet so I can't say what it would be.

**Comment by DerTanzschuh** [comment] 2018-07-03 13:52
I just stumbled upon this thread and am surprised of your statement about the compaction algorithm.
> I don't know whether it is possible to avoid the context being dereferenced as part of the compact operation

The last sentence in the overview to the algorithm is as follows :

> The final output is a JSON object **with an @context key**, if a non-empty context was given, where the JSON object is either result or a wrapper for it where result appears as the value of an (aliased) @graph key because result contained two or more items in an array.
https://www.w3.org/TR/json-ld-api/#compaction-algorithm

And if I try a similar example in the official [JSON-LD playground](https://json-ld.org/playground/) …

Input Object:
```
{
  "@context": "http://schema.org/",
  "@type": "http://schema.org/Person",
  "http://schema.org/jobTitle": "Professor",
  "http://schema.org/name": "Jane Doe",
  "http://schema.org/telephone": "(425) 123-4567",
  "http://schema.org/url": "http://www.janedoe.com"
}
```
Input Context:
```
{ "@context": "http://schema.org/" }
```

…  I get the following result:
```
{
  "@context": "http://schema.org/",
  "type": "Person",
  "jobTitle": "Professor",
  "name": "Jane Doe",
  "telephone": "(425) 123-4567",
  "schema:url": "http://www.janedoe.com"
}
```
[Show Live Sample](https://json-ld.org/playground/?startTab=tab-compacted&json-ld=%7B%22%40context%22%3A%22http%3A%2F%2Fschema.org%2F%22%2C%22%40type%22%3A%22http%3A%2F%2Fschema.org%2FPerson%22%2C%22http%3A%2F%2Fschema.org%2FjobTitle%22%3A%22Professor%22%2C%22http%3A%2F%2Fschema.org%2Fname%22%3A%22Jane%20Doe%22%2C%22http%3A%2F%2Fschema.org%2Ftelephone%22%3A%22(425)%20123-4567%22%2C%22http%3A%2F%2Fschema.org%2Furl%22%3A%22http%3A%2F%2Fwww.janedoe.com%22%7D&context=%7B%22%40context%22%3A%22http%3A%2F%2Fschema.org%2F%22%7D)

As you can see, the compacted result contains the @context property with the IRI proved with the context.

If I’m trying to do the same in Java exactly the way @fpservant did, the @context property is not provided in the result object.

**Comment by umbreak** [comment] 2020-09-14 12:35
I agree that must be a bug. I've just reported the same in this [new issue](https://github.com/jsonld-java/jsonld-java/issues/295) to later find out it is has been already reported here

**Closed** 2020-09-23 20:21 UTC
Labels: Integration, Jena
